// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLnUYBHgZ8b0mJmXYvuBO6u8msMxn8OnA',
    appId: '1:419492633359:web:12044452e1f8bc86d57c7a',
    messagingSenderId: '419492633359',
    projectId: 'authentication-practice-ad7c5',
    authDomain: 'authentication-practice-ad7c5.firebaseapp.com',
    storageBucket: 'authentication-practice-ad7c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYh9eDNc_GaRdOZ8I688DMnpyciUi01Qc',
    appId: '1:419492633359:android:81d9cd8a0e468a1dd57c7a',
    messagingSenderId: '419492633359',
    projectId: 'authentication-practice-ad7c5',
    storageBucket: 'authentication-practice-ad7c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Av7VUf9d9f1sLEYkSXejIUVWnsCu68s',
    appId: '1:419492633359:ios:1c6e127d8498030bd57c7a',
    messagingSenderId: '419492633359',
    projectId: 'authentication-practice-ad7c5',
    storageBucket: 'authentication-practice-ad7c5.firebasestorage.app',
    iosBundleId: 'com.example.brewCrew',
  );
}
